// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DcimUIClient is the client API for DcimUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DcimUIClient interface {
	// ListRackSpecs returns a list of Rack(s) that can be started through the UI.
	ListRackSpecs(ctx context.Context, in *ListRackSpecsRequest, opts ...grpc.CallOption) (DcimUI_ListRackSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type dcimUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDcimUIClient(cc grpc.ClientConnInterface) DcimUIClient {
	return &dcimUIClient{cc}
}

func (c *dcimUIClient) ListRackSpecs(ctx context.Context, in *ListRackSpecsRequest, opts ...grpc.CallOption) (DcimUI_ListRackSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DcimUI_ServiceDesc.Streams[0], "/v1.DcimUI/ListRackSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &dcimUIListRackSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DcimUI_ListRackSpecsClient interface {
	Recv() (*ListRackSpecsResponse, error)
	grpc.ClientStream
}

type dcimUIListRackSpecsClient struct {
	grpc.ClientStream
}

func (x *dcimUIListRackSpecsClient) Recv() (*ListRackSpecsResponse, error) {
	m := new(ListRackSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dcimUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DcimUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DcimUIServer is the server API for DcimUI service.
// All implementations must embed UnimplementedDcimUIServer
// for forward compatibility
type DcimUIServer interface {
	// ListRackSpecs returns a list of Rack(s) that can be started through the UI.
	ListRackSpecs(*ListRackSpecsRequest, DcimUI_ListRackSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDcimUIServer()
}

// UnimplementedDcimUIServer must be embedded to have forward compatible implementations.
type UnimplementedDcimUIServer struct {
}

func (UnimplementedDcimUIServer) ListRackSpecs(*ListRackSpecsRequest, DcimUI_ListRackSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListRackSpecs not implemented")
}
func (UnimplementedDcimUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDcimUIServer) mustEmbedUnimplementedDcimUIServer() {}

// UnsafeDcimUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DcimUIServer will
// result in compilation errors.
type UnsafeDcimUIServer interface {
	mustEmbedUnimplementedDcimUIServer()
}

func RegisterDcimUIServer(s grpc.ServiceRegistrar, srv DcimUIServer) {
	s.RegisterService(&DcimUI_ServiceDesc, srv)
}

func _DcimUI_ListRackSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRackSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DcimUIServer).ListRackSpecs(m, &dcimUIListRackSpecsServer{stream})
}

type DcimUI_ListRackSpecsServer interface {
	Send(*ListRackSpecsResponse) error
	grpc.ServerStream
}

type dcimUIListRackSpecsServer struct {
	grpc.ServerStream
}

func (x *dcimUIListRackSpecsServer) Send(m *ListRackSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DcimUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcimUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DcimUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcimUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DcimUI_ServiceDesc is the grpc.ServiceDesc for DcimUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DcimUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DcimUI",
	HandlerType: (*DcimUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DcimUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListRackSpecs",
			Handler:       _DcimUI_ListRackSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dcim-ui.proto",
}
